apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-db-api
  labels:
    app: vector-db-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vector-db-api
  template:
    metadata:
      labels:
        app: vector-db-api
    spec:
      containers:
        - name: vector-db-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80