apiVersion: v1
kind: Service
metadata:
  name: vector-db-api
  labels:
    app: vector-db-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: vector-db-api